### ISSUE TITLE
Change Database

### ISSUE THREAD

**Issue by dantel19** [dantel19/profile-manager#25]
Change the database in this way:
- remove the relation between User and Profile.
- add a relation between User and Information.
- add Category table and add a relation beetween Information and Category

Make the datamodel conforming to the database changes

**Comment by dantel19** [comment]
Closed with commit 40061db

**Comment by alexander-perucci** [comment]
1. Change the name of the table `Information_Profile` to `Profile_Information` and the related class.
2. Change the name of the table `Information_User` to `User_Information` and the related class.
3. Fix the license in the Category class. Please **you mustn't use** `find` and `replace` but you should use the refactor functionality provided by Eclipse !!
4. Add the `Category` class in the `persistence.xml` .
5. I'm not sure that the solution that you have provide in order to mapping many-to-many association with extra columns is it correct, please check here [Java Persistence with Hibernate](https://www.manning.com/books/java-persistence-with-hibernate). Need you the class `InformationProfileId` in order to resolve this problem #27 ?
6. If you need to override `hashCode` and `equals` methods please use Eclipse: right click on the class -> source -> generate hashCode() and equals() ...
7. If you need to generate the property `serialVersionUID` Eclipse will generate it for you.

**Comment by dantel19** [comment]
Closed with commit 81b8964
